dist: trusty
language: node_js
node_js:
- '8'
before_script:
  - npm install -g bower web-component-tester
  - bower install
script: xvfb-run wct
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable